---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Clearly, there is a need for a fast and scalable algorithm to automate the process of selecting
models with the aim of forecasting. We refer to this process as forecast model selection. There
have been several recent studies on the use of meta-learning approaches to automate forecast
model selection based on features computed from the time series (Shah 1997; Prudêncio &
Ludermir 2004; Lemke & Gabrys 2010; Kück, Crone & Freitag 2016). A meta-learning approach
provides systematic guidance on model selection based on knowledge acquired from historical
data sets. The key idea is that forecast model selection is posed as a supervised learning task.
Each time series in the metadata set is represented as a vector of features and labelled according
to the best forecast model (for example, the model with the lowest mean absolute scaled error
(MASE) over a test set). Then a meta-learner is trained to identify a suitable forecast model
(usually a machine learning algorithm is used).