---
title: "two-way"
author: "Thiyanga Talagala"
date: "14/11/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Mcomp)
library(ggplot2)
library(grid)
library(gridExtra)
library(ggrepel)
library(png)
library(tsfeatures)
library(tidyverse)
library(ggpubr)
library(reshape2)
#devtools::install_github("thomasp85/patchwork")
library(patchwork)
library(Hmisc)
```

```{r}
load("~/PhD_journey/fforms/data/HPCfiles/lmres_acf1.linearityrmout.y.rda")
colNamesls <- colnames(lmres_acf1.linearityrmout.y)[27:36]

keep.modelnames <- c("ARIMA", "ARMA.AR.MA", "ETS.dampedtrend", "ETS.notrendnoseasonal",
                     "ETS.trend", "nn", "rw", "rwd", "theta", "wn")
keepy <- c(keep.modelnames, c("lmres_acf1", "linearity"))
lmres_acf1.linearityrmout.y <- lmres_acf1.linearityrmout.y[, names(lmres_acf1.linearityrmout.y) %in% keepy]
lmres_acf1.linearityrmout.y.long <- gather(lmres_acf1.linearityrmout.y, class, probability, "ARIMA":"wn", factor_key = TRUE)
lmres_acf1.linearityrmout.y.long <- lmres_acf1.linearityrmout.y.long %>%
  mutate(class = recode(class, nn="nn",
                        theta = "theta",
                        wn = "wn",
                        "ARMA.AR.MA" = "ARMA",
                        ARIMA = "ARIMA",
                        "ETS.notrendnoseasonal" = "ETS_NTNS",
                        "ETS.dampedtrend" = "ETS_DT",
                        "ETS.trend" = "ETS_T",
                        "rwd" = "rwd",
                        "rw" = "rw" ))
lmres_acf1.linearityrmout.y.long$class <- factor(lmres_acf1.linearityrmout.y.long$class,
                                              levels = c("rw", "rwd", "ETS_T", "ETS_DT", "ETS_NTNS",
                                                         "ARIMA", "ARMA", "wn", "theta", "nn" ))

lmres_acf1.linearityrmout.y.long %>%
  ggplot(aes(x = lmres_acf1, y = linearity, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=5) +
  scale_fill_viridis_c(option = "A", direction = -1, breaks=c(0,0.45,20),
                       limits=c(0,0.45))+
  theme(strip.text.x = element_text(size = 10))+ylim(-10,10)


```

```{r}
load("~/PhD_journey/fforms/data/HPCfiles/curvature.linearityrmout.y.rda")
colNamesls <- colnames(curvature.linearityrmout.y)[27:36]

keep.modelnames <- c("ARIMA", "ARMA.AR.MA", "ETS.dampedtrend", "ETS.notrendnoseasonal",
                     "ETS.trend", "nn", "rw", "rwd", "theta", "wn")
keepy <- c(keep.modelnames, c("curvature", "linearity"))
curvature.linearityrmout.y <- curvature.linearityrmout.y[, names(curvature.linearityrmout.y) %in% keepy]
curvature.linearityrmout.y.long <- gather(curvature.linearityrmout.y, class, probability, "ARIMA":"wn", factor_key = TRUE)
curvature.linearityrmout.y.long <- curvature.linearityrmout.y.long %>%
  mutate(class = recode(class, nn="nn",
                        theta = "theta",
                        wn = "wn",
                        "ARMA.AR.MA" = "ARMA",
                        ARIMA = "ARIMA",
                        "ETS.notrendnoseasonal" = "ETS_NTNS",
                        "ETS.dampedtrend" = "ETS_DT",
                        "ETS.trend" = "ETS_T",
                        "rwd" = "rwd",
                        "rw" = "rw" ))
curvature.linearityrmout.y.long$class <- factor(curvature.linearityrmout.y.long$class,
                                              levels = c("rw", "rwd", "ETS_T", "ETS_DT", "ETS_NTNS",
                                                         "ARIMA", "ARMA", "wn", "theta", "nn" ))

curvature.linearityrmout.y.long %>%
  ggplot(aes(x = curvature, y = linearity, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=5) +
  scale_fill_viridis_c(option = "A", direction = -1, breaks=c(0,0.45,20),
                       limits=c(0,0.45))+
  theme(strip.text.x = element_text(size = 10))+ylim(-10,10)


```


```{r}
load("~/PhD_journey/fforms/data/HPCfiles/diff1y_acf1.linearityrmout.y.rda")
colNamesls <- colnames(diff1y_acf1.linearityrmout.y)[27:36]

keep.modelnames <- c("ARIMA", "ARMA.AR.MA", "ETS.dampedtrend", "ETS.notrendnoseasonal",
                     "ETS.trend", "nn", "rw", "rwd", "theta", "wn")
keepy <- c(keep.modelnames, c("diff1y_acf1", "linearity"))
diff1y_acf1.linearityrmout.y <- diff1y_acf1.linearityrmout.y[, names(diff1y_acf1.linearityrmout.y) %in% keepy]
diff1y_acf1.linearityrmout.y.long <- gather(diff1y_acf1.linearityrmout.y, class, probability, "ARIMA":"wn", factor_key = TRUE)
diff1y_acf1.linearityrmout.y.long <- diff1y_acf1.linearityrmout.y.long %>%
  mutate(class = recode(class, nn="nn",
                        theta = "theta",
                        wn = "wn",
                        "ARMA.AR.MA" = "ARMA",
                        ARIMA = "ARIMA",
                        "ETS.notrendnoseasonal" = "ETS_NTNS",
                        "ETS.dampedtrend" = "ETS_DT",
                        "ETS.trend" = "ETS_T",
                        "rwd" = "rwd",
                        "rw" = "rw" ))
diff1y_acf1.linearityrmout.y.long$class <- factor(diff1y_acf1.linearityrmout.y.long$class,
                                              levels = c("rw", "rwd", "ETS_T", "ETS_DT", "ETS_NTNS",
                                                         "ARIMA", "ARMA", "wn", "theta", "nn" ))

diff1y_acf1.linearityrmout.y.long %>%
  ggplot(aes(x = diff1y_acf1, y = linearity, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=5) +
  scale_fill_viridis_c(option = "A", direction = -1, breaks=c(0,0.4,100),
                       limits=c(0,0.4))+
  theme(strip.text.x = element_text(size = 10))+ylim(-10,10)


```


```{r}
load("data/HPCfiles/stability.linearityrmout.y.rda")
colNamesls <- colnames(stability.linearityrmout.y)[27:36]

keep.modelnames <- c("ARIMA", "ARMA.AR.MA", "ETS.dampedtrend", "ETS.notrendnoseasonal",
                     "ETS.trend", "nn", "rw", "rwd", "theta", "wn")
keepy <- c(keep.modelnames, c("stability", "linearity"))
stability.linearityrmout.y <- stability.linearityrmout.y[, names(stability.linearityrmout.y) %in% keepy]
stability.linearityrmout.y.long <- gather(stability.linearityrmout.y, class, probability, "ARIMA":"wn", factor_key = TRUE)
stability.linearityrmout.y.long <- stability.linearityrmout.y.long %>%
  mutate(class = recode(class, nn="nn",
                        theta = "theta",
                        wn = "wn",
                        "ARMA.AR.MA" = "ARMA",
                        ARIMA = "ARIMA",
                        "ETS.notrendnoseasonal" = "ETS_NTNS",
                        "ETS.dampedtrend" = "ETS_DT",
                        "ETS.trend" = "ETS_T",
                        "rwd" = "rwd",
                        "rw" = "rw" ))
stability.linearityrmout.y.long$class <- factor(stability.linearityrmout.y.long$class,
                                              levels = c("rw", "rwd", "ETS_T", "ETS_DT", "ETS_NTNS",
                                                         "ARIMA", "ARMA", "wn", "theta", "nn" ))

stability.linearityrmout.y.long %>%
  ggplot(aes(x = stability, y = linearity, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=5) +
  scale_fill_viridis_c(option = "A", direction = -1, breaks=c(0,0.2,100),
                       limits=c(0,0.2))+
  theme(strip.text.x = element_text(size = 10))+ylim(-10,10)


```

```{r}
load("data/HPCfiles/y_pacf5.linearityrmout.y.rda")
colNamesls <- colnames(y_pacf5.linearityrmout.y)[27:36]

keep.modelnames <- c("ARIMA", "ARMA.AR.MA", "ETS.dampedtrend", "ETS.notrendnoseasonal",
                     "ETS.trend", "nn", "rw", "rwd", "theta", "wn")
keepy <- c(keep.modelnames, c("y_pacf5", "linearity"))
y_pacf5.linearityrmout.y <- y_pacf5.linearityrmout.y[, names(y_pacf5.linearityrmout.y) %in% keepy]
y_pacf5.linearityrmout.y.long <- gather(y_pacf5.linearityrmout.y, class, probability, "ARIMA":"wn", factor_key = TRUE)
y_pacf5.linearityrmout.y.long <- y_pacf5.linearityrmout.y.long %>%
  mutate(class = recode(class, nn="nn",
                        theta = "theta",
                        wn = "wn",
                        "ARMA.AR.MA" = "ARMA",
                        ARIMA = "ARIMA",
                        "ETS.notrendnoseasonal" = "ETS_NTNS",
                        "ETS.dampedtrend" = "ETS_DT",
                        "ETS.trend" = "ETS_T",
                        "rwd" = "rwd",
                        "rw" = "rw" ))
y_pacf5.linearityrmout.y.long$class <- factor(y_pacf5.linearityrmout.y.long$class,
                                              levels = c("rw", "rwd", "ETS_T", "ETS_DT", "ETS_NTNS",
                                                         "ARIMA", "ARMA", "wn", "theta", "nn" ))

y_pacf5.linearityrmout.y.long %>%
  ggplot(aes(x = y_pacf5, y = linearity, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=5) +
  scale_fill_viridis_c(option = "A", direction = -1, breaks=c(0,0.25,100),
                       limits=c(0,0.25))+
  theme(strip.text.x = element_text(size = 10))+ylim(-10,10)



```


```{r}
load("data/HPCfiles/100grid/y_acf1.linearityrmout.y.rda")
colNamesls <- colnames(y_acf1.linearityrmout.y)[27:36]

keep.modelnames <- c("ARIMA", "ARMA.AR.MA", "ETS.dampedtrend", "ETS.notrendnoseasonal",
                     "ETS.trend", "nn", "rw", "rwd", "theta", "wn")
keepy <- c(keep.modelnames, c("y_acf1", "linearity"))
y_acf1.linearityrmout.y <- y_acf1.linearityrmout.y[, names(y_acf1.linearityrmout.y) %in% keepy]
y_acf1.linearityrmout.y.long <- gather(y_acf1.linearityrmout.y, class, probability, "ARIMA":"wn", factor_key = TRUE)
y_acf1.linearityrmout.y.long <- y_acf1.linearityrmout.y.long %>%
  mutate(class = recode(class, nn="nn",
                        theta = "theta",
                        wn = "wn",
                        "ARMA.AR.MA" = "ARMA",
                        ARIMA = "ARIMA",
                        "ETS.notrendnoseasonal" = "ETS_NTNS",
                        "ETS.dampedtrend" = "ETS_DT",
                        "ETS.trend" = "ETS_T",
                        "rwd" = "rwd",
                        "rw" = "rw" ))
y_acf1.linearityrmout.y.long$class <- factor(y_acf1.linearityrmout.y.long$class,
                                              levels = c("rw", "rwd", "ETS_T", "ETS_DT", "ETS_NTNS",
                                                         "ARIMA", "ARMA", "wn", "theta", "nn" ))

y_acf1.linearityrmout.y.long %>%
  ggplot(aes(x = y_acf1, y = linearity, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=5) +
  scale_fill_viridis_c(option = "A", direction = -1, breaks=c(0,0.25,100),
                       limits=c(0,0.25))+
  theme(strip.text.x = element_text(size = 10))+ylim(-10,10)


```

```{r}
load("data/HPCfiles/y_pacf5.linearity.m.rda")
colNamesds <-colnames(y_pacf5.linearity.m)[32:48]
keep.modelnames <- c("ARIMA", "ARMA.AR.MA", "ETS.dampedtrend", "ETS.dampedtrendseasonal",
                     "ETS.notrendnoseasonal", "ETS.seasonal", 
                     "ETS.trend","ETS.trendseasonal"  ,"nn", "rw",
                     "rwd", "SARIMA","snaive","stlar","tbats","theta", "wn")
keepm <- c(keep.modelnames, c("y_pacf5", "linearity"))
y_pacf5.linearity.m <- y_pacf5.linearity.m[, names(y_pacf5.linearity.m) %in% keepm]
y_pacf5.linearity.m.long <- gather(y_pacf5.linearity.m, class, probability, "ARIMA":"wn", factor_key = TRUE)
y_pacf5.linearity.m.long <- y_pacf5.linearity.m.long %>%
  mutate(class = recode(class, "ARIMA"="ARIMA", "ARMA.AR.MA"="ARMA", 
                        "ETS.dampedtrend"="ETS_DT", "ETS.dampedtrendseasonal"="ETS_DTS",
                        "ETS.notrendnoseasonal"="ETS_NTNS", "ETS.seasonal"="ETS_S", 
                        "ETS.trend"="ETS_T","ETS.trendseasonal"="ETS_TS"  ,"nn"="nn", "rw"="rw",
                        "rwd"="rwd", "SARIMA"="SARIMA","snaive"="snaive","stlar"="stlar","tbats"="tbats","theta"="theta", "wn"="wn"))
y_pacf5.linearity.m.long$class <- factor(y_pacf5.linearity.m.long$class,
                                             levels = c("snaive","rw", "rwd", "ETS_NTNS","ETS_DT", "ETS_T", "ETS_DTS",
                                                        "ETS_TS", "ETS_S","tbats","stlar", "SARIMA",
                                                        "ARIMA", "ARMA", "wn", "theta", "nn" ))




y_pacf5.linearity.m.long %>%
  ggplot(aes(x = y_pacf5, y = linearity, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=6) +
  scale_fill_viridis_c(breaks=c(0,0.5,100),
                       limits=c(0,0.5), option = "A", direction = -1)+
  theme(strip.text.x = element_text(size = 12))



```

```{r}
## 0.2, rwd, stlar, theta, nn
load("data/HPCfiles/diff1y_acf1.linearity.m.rda")
colNamesds <-colnames(diff1y_acf1.linearity.m)[32:48]
keep.modelnames <- c("ARIMA", "ARMA.AR.MA", "ETS.dampedtrend", "ETS.dampedtrendseasonal",
                     "ETS.notrendnoseasonal", "ETS.seasonal", 
                     "ETS.trend","ETS.trendseasonal"  ,"nn", "rw",
                     "rwd", "SARIMA","snaive","stlar","tbats","theta", "wn")
keepm <- c(keep.modelnames, c("diff1y_acf1", "linearity"))
diff1y_acf1.linearity.m <- diff1y_acf1.linearity.m[, names(diff1y_acf1.linearity.m) %in% keepm]
diff1y_acf1.linearity.m.long <- gather(diff1y_acf1.linearity.m, class, probability, "ARIMA":"wn", factor_key = TRUE)
diff1y_acf1.linearity.m.long <- diff1y_acf1.linearity.m.long %>%
  mutate(class = recode(class, "ARIMA"="ARIMA", "ARMA.AR.MA"="ARMA", 
                        "ETS.dampedtrend"="ETS_DT", "ETS.dampedtrendseasonal"="ETS_DTS",
                        "ETS.notrendnoseasonal"="ETS_NTNS", "ETS.seasonal"="ETS_S", 
                        "ETS.trend"="ETS_T","ETS.trendseasonal"="ETS_TS"  ,"nn"="nn", "rw"="rw",
                        "rwd"="rwd", "SARIMA"="SARIMA","snaive"="snaive","stlar"="stlar","tbats"="tbats","theta"="theta", "wn"="wn"))
diff1y_acf1.linearity.m.long$class <- factor(diff1y_acf1.linearity.m.long$class,
                                             levels = c("snaive","rw", "rwd", "ETS_NTNS","ETS_DT", "ETS_T", "ETS_DTS",
                                                        "ETS_TS", "ETS_S","tbats","stlar", "SARIMA",
                                                        "ARIMA", "ARMA", "wn", "theta", "nn" ))




diff1y_acf1.linearity.m.long %>%
  ggplot(aes(x = diff1y_acf1, y = linearity, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=6) +
  scale_fill_viridis_c(breaks=c(0,0.5,100),
                       limits=c(0,0.5), option = "A", direction = -1)+
  theme(strip.text.x = element_text(size = 12))



```

```{r}
## 0.2, rwd, stlar, theta, nn
load("data/HPCfiles/sediff_seacf1.linearity.m.rda")
colNamesds <-colnames(sediff_seacf1.linearity.m)[32:48]
keep.modelnames <- c("ARIMA", "ARMA.AR.MA", "ETS.dampedtrend", "ETS.dampedtrendseasonal",
                     "ETS.notrendnoseasonal", "ETS.seasonal", 
                     "ETS.trend","ETS.trendseasonal"  ,"nn", "rw",
                     "rwd", "SARIMA","snaive","stlar","tbats","theta", "wn")
keepm <- c(keep.modelnames, c("sediff_seacf1", "linearity"))
sediff_seacf1.linearity.m <- sediff_seacf1.linearity.m[, names(sediff_seacf1.linearity.m) %in% keepm]
sediff_seacf1.linearity.m.long <- gather(sediff_seacf1.linearity.m, class, probability, "ARIMA":"wn", factor_key = TRUE)
sediff_seacf1.linearity.m.long <- sediff_seacf1.linearity.m.long %>%
  mutate(class = recode(class, "ARIMA"="ARIMA", "ARMA.AR.MA"="ARMA", 
                        "ETS.dampedtrend"="ETS_DT", "ETS.dampedtrendseasonal"="ETS_DTS",
                        "ETS.notrendnoseasonal"="ETS_NTNS", "ETS.seasonal"="ETS_S", 
                        "ETS.trend"="ETS_T","ETS.trendseasonal"="ETS_TS"  ,"nn"="nn", "rw"="rw",
                        "rwd"="rwd", "SARIMA"="SARIMA","snaive"="snaive","stlar"="stlar","tbats"="tbats","theta"="theta", "wn"="wn"))
sediff_seacf1.linearity.m.long$class <- factor(sediff_seacf1.linearity.m.long$class,
                                             levels = c("snaive","rw", "rwd", "ETS_NTNS","ETS_DT", "ETS_T", "ETS_DTS",
                                                        "ETS_TS", "ETS_S","tbats","stlar", "SARIMA",
                                                        "ARIMA", "ARMA", "wn", "theta", "nn" ))




sediff_seacf1.linearity.m.long %>%
  ggplot(aes(x = sediff_seacf1, y = linearity, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=6) +
  scale_fill_viridis_c(breaks=c(0,0.1,100),
                       limits=c(0,0.1), option = "A", direction = -1)+
  theme(strip.text.x = element_text(size = 1))



```

```{r}
## 0.2, rwd, stlar, theta, nn
load("data/HPCfiles/diff1y_acf5.linearity.m.rda")
colNamesds <-colnames(diff1y_acf5.linearity.m)[32:48]
keep.modelnames <- c("ARIMA", "ARMA.AR.MA", "ETS.dampedtrend", "ETS.dampedtrendseasonal",
                     "ETS.notrendnoseasonal", "ETS.seasonal", 
                     "ETS.trend","ETS.trendseasonal"  ,"nn", "rw",
                     "rwd", "SARIMA","snaive","stlar","tbats","theta", "wn")
keepm <- c(keep.modelnames, c("diff1y_acf5", "linearity"))
diff1y_acf5.linearity.m <- diff1y_acf5.linearity.m[, names(diff1y_acf5.linearity.m) %in% keepm]
diff1y_acf5.linearity.m.long <- gather(diff1y_acf5.linearity.m, class, probability, "ARIMA":"wn", factor_key = TRUE)
diff1y_acf5.linearity.m.long <- diff1y_acf5.linearity.m.long %>%
  mutate(class = recode(class, "ARIMA"="ARIMA", "ARMA.AR.MA"="ARMA", 
                        "ETS.dampedtrend"="ETS_DT", "ETS.dampedtrendseasonal"="ETS_DTS",
                        "ETS.notrendnoseasonal"="ETS_NTNS", "ETS.seasonal"="ETS_S", 
                        "ETS.trend"="ETS_T","ETS.trendseasonal"="ETS_TS"  ,"nn"="nn", "rw"="rw",
                        "rwd"="rwd", "SARIMA"="SARIMA","snaive"="snaive","stlar"="stlar","tbats"="tbats","theta"="theta", "wn"="wn"))
diff1y_acf5.linearity.m.long$class <- factor(diff1y_acf5.linearity.m.long$class,
                                             levels = c("snaive","rw", "rwd", "ETS_NTNS","ETS_DT", "ETS_T", "ETS_DTS",
                                                        "ETS_TS", "ETS_S","tbats","stlar", "SARIMA",
                                                        "ARIMA", "ARMA", "wn", "theta", "nn" ))




diff1y_acf5.linearity.m.long %>%
  ggplot(aes(x = diff1y_acf5, y = linearity, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=6) +
  scale_fill_viridis_c(breaks=c(0,0.1,100),
                       limits=c(0,0.1), option = "A", direction = -1)+
  theme(strip.text.x = element_text(size = 1))
```

```{r}
## 0.2, rwd, stlar, theta, nn
load("data/HPCfiles/stability.linearity.m.rda")
colNamesds <-colnames(stability.linearity.m)[32:48]
keep.modelnames <- c("ARIMA", "ARMA.AR.MA", "ETS.dampedtrend", "ETS.dampedtrendseasonal",
                     "ETS.notrendnoseasonal", "ETS.seasonal", 
                     "ETS.trend","ETS.trendseasonal"  ,"nn", "rw",
                     "rwd", "SARIMA","snaive","stlar","tbats","theta", "wn")
keepm <- c(keep.modelnames, c("stability", "linearity"))
stability.linearity.m <- stability.linearity.m[, names(stability.linearity.m) %in% keepm]
stability.linearity.m.long <- gather(stability.linearity.m, class, probability, "ARIMA":"wn", factor_key = TRUE)
stability.linearity.m.long <- stability.linearity.m.long %>%
  mutate(class = recode(class, "ARIMA"="ARIMA", "ARMA.AR.MA"="ARMA", 
                        "ETS.dampedtrend"="ETS_DT", "ETS.dampedtrendseasonal"="ETS_DTS",
                        "ETS.notrendnoseasonal"="ETS_NTNS", "ETS.seasonal"="ETS_S", 
                        "ETS.trend"="ETS_T","ETS.trendseasonal"="ETS_TS"  ,"nn"="nn", "rw"="rw",
                        "rwd"="rwd", "SARIMA"="SARIMA","snaive"="snaive","stlar"="stlar","tbats"="tbats","theta"="theta", "wn"="wn"))
stability.linearity.m.long$class <- factor(stability.linearity.m.long$class,
                                             levels = c("snaive","rw", "rwd", "ETS_NTNS","ETS_DT", "ETS_T", "ETS_DTS",
                                                        "ETS_TS", "ETS_S","tbats","stlar", "SARIMA",
                                                        "ARIMA", "ARMA", "wn", "theta", "nn" ))




stability.linearity.m.long %>%
  ggplot(aes(x = stability, y = linearity, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=6) +
  scale_fill_viridis_c(breaks=c(0,0.2,100),
                       limits=c(0,0.2), option = "A", direction = -1)+
  theme(strip.text.x = element_text(size = 1))
```

```{r}
load("data/HPCfiles/e_acf1.linearity.m.rda")
colNamesds <-colnames(e_acf1.linearity.m)[32:48]
keep.modelnames <- c("ARIMA", "ARMA.AR.MA", "ETS.dampedtrend", "ETS.dampedtrendseasonal",
                     "ETS.notrendnoseasonal", "ETS.seasonal", 
                     "ETS.trend","ETS.trendseasonal"  ,"nn", "rw",
                     "rwd", "SARIMA","snaive","stlar","tbats","theta", "wn")
keepm <- c(keep.modelnames, c("e_acf1", "linearity"))
e_acf1.linearity.m <- e_acf1.linearity.m[, names(e_acf1.linearity.m) %in% keepm]
e_acf1.linearity.m.long <- gather(e_acf1.linearity.m, class, probability, "ARIMA":"wn", factor_key = TRUE)
e_acf1.linearity.m.long <- e_acf1.linearity.m.long %>%
  mutate(class = recode(class, "ARIMA"="ARIMA", "ARMA.AR.MA"="ARMA", 
                        "ETS.dampedtrend"="ETS_DT", "ETS.dampedtrendseasonal"="ETS_DTS",
                        "ETS.notrendnoseasonal"="ETS_NTNS", "ETS.seasonal"="ETS_S", 
                        "ETS.trend"="ETS_T","ETS.trendseasonal"="ETS_TS"  ,"nn"="nn", "rw"="rw",
                        "rwd"="rwd", "SARIMA"="SARIMA","snaive"="snaive","stlar"="stlar","tbats"="tbats","theta"="theta", "wn"="wn"))
e_acf1.linearity.m.long$class <- factor(e_acf1.linearity.m.long$class,
                                             levels = c("snaive","rw", "rwd", "ETS_NTNS","ETS_DT", "ETS_T", "ETS_DTS",
                                                        "ETS_TS", "ETS_S","tbats","stlar", "SARIMA",
                                                        "ARIMA", "ARMA", "wn", "theta", "nn" ))




e_acf1.linearity.m.long %>%
  ggplot(aes(x = e_acf1, y = linearity, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=6) +
  scale_fill_viridis_c(breaks=c(0,0.1,100),
                       limits=c(0,0.1), option = "A", direction = -1)+
  theme(strip.text.x = element_text(size = 1))
```


```{r}
load("data/HPCfiles/hwalpha.linearity.m.rda")
colNamesds <-colnames(hwalpha.linearity.m)[32:48]
keep.modelnames <- c("ARIMA", "ARMA.AR.MA", "ETS.dampedtrend", "ETS.dampedtrendseasonal",
                     "ETS.notrendnoseasonal", "ETS.seasonal", 
                     "ETS.trend","ETS.trendseasonal"  ,"nn", "rw",
                     "rwd", "SARIMA","snaive","stlar","tbats","theta", "wn")
keepm <- c(keep.modelnames, c("hwalpha", "linearity"))
hwalpha.linearity.m <- hwalpha.linearity.m[, names(hwalpha.linearity.m) %in% keepm]
hwalpha.linearity.m.long <- gather(hwalpha.linearity.m, class, probability, "ARIMA":"wn", factor_key = TRUE)
hwalpha.linearity.m.long <- hwalpha.linearity.m.long %>%
  mutate(class = recode(class, "ARIMA"="ARIMA", "ARMA.AR.MA"="ARMA", 
                        "ETS.dampedtrend"="ETS_DT", "ETS.dampedtrendseasonal"="ETS_DTS",
                        "ETS.notrendnoseasonal"="ETS_NTNS", "ETS.seasonal"="ETS_S", 
                        "ETS.trend"="ETS_T","ETS.trendseasonal"="ETS_TS"  ,"nn"="nn", "rw"="rw",
                        "rwd"="rwd", "SARIMA"="SARIMA","snaive"="snaive","stlar"="stlar","tbats"="tbats","theta"="theta", "wn"="wn"))
hwalpha.linearity.m.long$class <- factor(hwalpha.linearity.m.long$class,
                                             levels = c("snaive","rw", "rwd", "ETS_NTNS","ETS_DT", "ETS_T", "ETS_DTS",
                                                        "ETS_TS", "ETS_S","tbats","stlar", "SARIMA",
                                                        "ARIMA", "ARMA", "wn", "theta", "nn" ))




hwalpha.linearity.m.long %>%
  ggplot(aes(x = hwalpha, y = linearity, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=6) +
  scale_fill_viridis_c(breaks=c(0,0.15,100),
                       limits=c(0,0.15), option = "A", direction = -1)+
  theme(strip.text.x = element_text(size = 1))
```


```{r}
load("data/HPCfiles/N.linearity.m.rda")
colNamesds <-colnames(N.linearity.m)[32:48]
keep.modelnames <- c("ARIMA", "ARMA.AR.MA", "ETS.dampedtrend", "ETS.dampedtrendseasonal",
                     "ETS.notrendnoseasonal", "ETS.seasonal", 
                     "ETS.trend","ETS.trendseasonal"  ,"nn", "rw",
                     "rwd", "SARIMA","snaive","stlar","tbats","theta", "wn")
keepm <- c(keep.modelnames, c("N", "linearity"))
N.linearity.m <- N.linearity.m[, names(N.linearity.m) %in% keepm]
N.linearity.m.long <- gather(N.linearity.m, class, probability, "ARIMA":"wn", factor_key = TRUE)
N.linearity.m.long <- N.linearity.m.long %>%
  mutate(class = recode(class, "ARIMA"="ARIMA", "ARMA.AR.MA"="ARMA", 
                        "ETS.dampedtrend"="ETS_DT", "ETS.dampedtrendseasonal"="ETS_DTS",
                        "ETS.notrendnoseasonal"="ETS_NTNS", "ETS.seasonal"="ETS_S", 
                        "ETS.trend"="ETS_T","ETS.trendseasonal"="ETS_TS"  ,"nn"="nn", "rw"="rw",
                        "rwd"="rwd", "SARIMA"="SARIMA","snaive"="snaive","stlar"="stlar","tbats"="tbats","theta"="theta", "wn"="wn"))
N.linearity.m.long$class <- factor(N.linearity.m.long$class,
                                             levels = c("snaive","rw", "rwd", "ETS_NTNS","ETS_DT", "ETS_T", "ETS_DTS",
                                                        "ETS_TS", "ETS_S","tbats","stlar", "SARIMA",
                                                        "ARIMA", "ARMA", "wn", "theta", "nn" ))




N.linearity.m.long %>%
  ggplot(aes(x = N, y = linearity, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=6) +
  scale_fill_viridis_c(breaks=c(0,0.2,100),
                       limits=c(0,0.2), option = "A", direction = -1)+
  theme(strip.text.x = element_text(size = 1))
```



```{r}
load("data/HPCfiles/diff1y_acf5.linearity.m.rda")
colNamesds <-colnames(diff1y_acf5.linearity.m)[32:48]
keep.modelnames <- c("ARIMA", "ARMA.AR.MA", "ETS.dampedtrend", "ETS.dampedtrendseasonal",
                     "ETS.notrendnoseasonal", "ETS.seasonal", 
                     "ETS.trend","ETS.trendseasonal"  ,"nn", "rw",
                     "rwd", "SARIMA","snaive","stlar","tbats","theta", "wn")
keepm <- c(keep.modelnames, c("diff1y_acf5", "linearity"))
diff1y_acf5.linearity.m <- diff1y_acf5.linearity.m[, names(diff1y_acf5.linearity.m) %in% keepm]
diff1y_acf5.linearity.m.long <- gather(diff1y_acf5.linearity.m, class, probability, "ARIMA":"wn", factor_key = TRUE)
diff1y_acf5.linearity.m.long <- diff1y_acf5.linearity.m.long %>%
  mutate(class = recode(class, "ARIMA"="ARIMA", "ARMA.AR.MA"="ARMA", 
                        "ETS.dampedtrend"="ETS_DT", "ETS.dampedtrendseasonal"="ETS_DTS",
                        "ETS.notrendnoseasonal"="ETS_NTNS", "ETS.seasonal"="ETS_S", 
                        "ETS.trend"="ETS_T","ETS.trendseasonal"="ETS_TS"  ,"nn"="nn", "rw"="rw",
                        "rwd"="rwd", "SARIMA"="SARIMA","snaive"="snaive","stlar"="stlar","tbats"="tbats","theta"="theta", "wn"="wn"))
diff1y_acf5.linearity.m.long$class <- factor(diff1y_acf5.linearity.m.long$class,
                                             levels = c("snaive","rw", "rwd", "ETS_NTNS","ETS_DT", "ETS_T", "ETS_DTS",
                                                        "ETS_TS", "ETS_S","tbats","stlar", "SARIMA",
                                                        "ARIMA", "ARMA", "wn", "theta", "nn" ))




diff1y_acf5.linearity.m.long %>%
  ggplot(aes(x = diff1y_acf5, y = linearity, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=6) +
  scale_fill_viridis_c(breaks=c(0,0.2,100),
                       limits=c(0,0.2), option = "A", direction = -1)+
  theme(strip.text.x = element_text(size = 1))
```


```{r}
linearity.sediff_seacf1.h <- load("data/HPCfiles/linearity.sediff_seacf1.h.rda")
colNamesss <- colnames(linearity.sediff_seacf1.h)[28:37]

keep.modelnames <- c("snaive", "rw", "rwd", "mstlarima", "mstlets", "tbats","stlar",
                     "theta","nn","wn")
keepd <- c(keep.modelnames, c("linearity", "sediff_seacf1"))
linearity.sediff_seacf1.h <- linearity.sediff_seacf1.h[, names(linearity.sediff_seacf1.h) %in% keepd]
linearity.sediff_seacf1.h.long <- gather(linearity.sediff_seacf1.h, class, probability, "mstlarima":"wn", factor_key = TRUE)
linearity.sediff_seacf1.h.long$class <- factor(linearity.sediff_seacf1.h.long$class,
                                                    levels = c("snaive", "rw", "rwd", "mstlarima", "mstlets", "tbats","stlar",
                                                               "theta","nn","wn"))

linearity.sediff_seacf1.h.long %>%
  ggplot(aes(x = linearity, y = sediff_seacf1, fill = probability)) +
  geom_raster() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~class, ncol=5) +
  scale_fill_viridis_c(option = "A", direction = -1, breaks=c(0,0.8,100),
                       limits=c(0,0.8))+
  theme(strip.text.x = element_text(size = 10))+ylab("sediff_seacf1")

```